### ISSUE TITLE
External hardware detection after boot.

### ISSUE THREAD

**Issue by onekillgithub** [koush/EFI-X99#10]
Some usb and external hard drives needs re-plugging after reboot to show up or work in Sierra.

Affected peripherals:
(ext hdd) Mybook Studio 6GB - Raid0 config - eSata
(ext hdd) Mybook 4GB - USB
(piano keys) Nectar Impact GX61 - USB
(usb 2 hub) D-Link DUB-H7
USB midi interface-cable, something something
I vaguely remember some other USB hubs also getting this. 

Peripherals that work without issues:
(previous sound card) Focusrite Scarlett 2i2 (first gen) (USB)
(sound card) Audient ID4 (USB)
(sound card) ESI GigaportHD+ (USB)
2 different bluetooth dongles (USB)
(printer) Canon iP2700
(mouse/keyboard) Logitech unifying receiver
(license dongle) Ilok 2 (note: had to reconnect it once)
(license dongle) eLicenser
4-port USB Hub with dongles
HDD dock - eSata and USB (Could have had problems with it before, but i seldom use it, so i might have forgotten about it.)

Now, to be clear, the affected items always work fine after i re-plug them. Also, all the internal SSDs always show up in Sierra, and all hard drives/SSD:s always show up in Windows 10. Both external hard drives are configured as eSATA, and I can't confirm how they work with this disabled. I will test this and update later.

I thought that the external hard drives might have been the problem, because they are old, but then my brand new keyboard has the same problem, so i figured it might be something else, and that's why I'm here now. I'm mostly surprised that the same problem persists on both USB and eSATA, and not exclusively to storage devices. Might this be a problem that can be solved with clover configurator?

Any help would be greatly appreciated!

Build:
Gigabyte GA-X99P-SLI, i7-6950X, 8 x 8GB Corsair Vengeance LED 3400MHz, 2 internal SATA SSDs, 1 M.2 Samsung SSD (mounted on mobo slot)(boot drive). Sierra 10.12.6 (16G29)

On a side note: I'm trying to get a Griffin Powermate Bluetooth to connect to it's software, but won't connect. The software can see it but nothing happens when i try to connect. It works great on an old mac mini running ML, and in Win 10 on the main machine. Apparently, talking to their support, I'm the only one with the problem, and they can't reproduce it, so i'm basically screwed, since the costs for shipping it back halfway around the globe isn't worth it if this problem can be solved eventually, somehow. Tested on all systems with both my BT dongles with the same result.  So now it acts as a paper weight. But I stay positive...

**Comment by koush** [comment]
feel free to reopen if this still occurs.
