### ISSUE TITLE
USB working at 1.1 speed

### ISSUE THREAD

**Issue by zilingzhang** [koush/EFI-X99#12]
Thank you for providing this amazing efi configurations, I have similar setup (GA-X99-Phoenix-SLI, GTX 1080), I applied it on 12.6 install, and work out of box. But all usb drives were running at usb 1.1 speed, and I fixed it by removing usb inject in plist, USBInjectAll.kext, XHCI-x99-injector.kext, and use the X99_Injector USB 3.kext from KGP's [post](https://www.tonymacx86.com/threads/the-perfect-customac-pro-x99-a-ii-i7-6950x-128gb-g-skill-tridentz-aorus-gtx-1080-ti-xtreme.211621/)

**Comment by koush** [comment]
merged
