### ISSUE TITLE
SSDT-NVMe-Pcc cannot generate new ssdt

### ISSUE THREAD

**Issue by jacoweb** [koush/EFI-X99#3]
hey there! Really nice guide! But i have some problems when generating a new SSDT. Because i have a diffrent drive.

// ACPI Error: Found unknown opcode 0x15 at AML address 0x7fa35b402e77 offset 0x3, ignoring (20100331/psloop-230)
// ACPI Warning: Found bad character(s) in name, repaired: [*H**]
//  (20100331/utmisc-898)
// ACPI Warning: Found bad character(s) in name, repaired: [*H**]
//  (20100331/utmisc-898)
// ACPI Error: Found unknown opcode 0x5 at AML address 0x7fa35b402e91 offset 0x1D, ignoring (20100331/psloop-230)
// ACPI Error: Found unknown opcode 0x4 at AML address 0x7fa35b402ea6 offset 0x32, ignoring (20100331/psloop-230)
// ACPI Warning: Found bad character(s) in name, repaired: [*H**]
//  (20100331/utmisc-898)
// ACPI Warning: Found bad character(s) in name, repaired: [*H**]
//  (20100331/utmisc-898)
// ACPI Error: Found unknown opcode 0x15 at AML address 0x7fa35b402e77 offset 0x3, ignoring (20100331/psloop-230)
// ACPI Warning: Found bad character(s) in name, repaired: [*H**]
//  (20100331/utmisc-898)
// ACPI Warning: Found bad character(s) in name, repaired: [*H**]
//  (20100331/utmisc-898)
// ACPI Error: Found unknown opcode 0x5 at AML address 0x7fa35b402e91 offset 0x1D, ignoring (20100331/psloop-230)
// ACPI Error: Found unknown opcode 0x4 at AML address 0x7fa35b402ea6 offset 0x32, ignoring (20100331/psloop-230)

So the SSDT is not working. Can you help me out?

**Comment by koush** [comment]
you using the script to generate an SSDT for your NVMe drive? The one checked in is specific to my motherboard and drive, and probably won't work for you.

https://github.com/koush/EFI-X99/blob/master/CLOVER/bin/generate-spoof-nvme.sh

**Comment by koush** [comment]
Also, if your device doesn't have an ACPI name, the script won't work at all. Check the README under patch-nvme for more info.

**Comment by jacoweb** [comment]
ahh thats why. I have the same motherboard, with GTX 970 and 6800k. And intel NVMe. I also get some usb errors on boot. USB is super slow. Do you know why? Is there any settings in the bios i need to fix? Have latest bios.

**Comment by koush** [comment]
the usb 2.0 ports seem really slow. use usb3 ports in the back.

**Comment by jacoweb** [comment]
USB 3.0 is also insane slow here. Is there any BIOS settings i need to fix?
I use your files with minimal config (just added new SSDT for GFX and the edit for voodooTSCSync / and NVMe SSDT for my Drive)

**Comment by koush** [comment]
no idea, sorry. haven't looked into it since I just use the USB 3 ports which work fine. If you find the fix, let me know, and I'll update this guide.

**Comment by jacoweb** [comment]
ok :) Because its slow on both. usb2 and usb3. I will let you know if i find a fix for it.

**Comment by koush** [comment]
i'd try disconnecting all usb devices and only connecting essential ones.

**Comment by jacoweb** [comment]
Hi again. All working perfect now. I dont know why, but i had connected the frontpanel USB ports to the port 2 on the motherboard, not USB port 1.

Now everyting works perfect. Also the NVMe.

Only one issue, i cant get the Thunderbolt driver to load. So i need to figure out whats wrong there.

**Comment by koush** [comment]
Interesting. Let me see what my motherboard is connected to.

What do you mean you can't get the thunderbolt driver to load? How can you tell? My USB-C port works fine, so I presume thunderbolt is working.

**Comment by koush** [comment]
Just checked, I'm hooked to USB_1. Nothing connected to USB_2.

**Comment by koush** [comment]
updated the guide with a note regarding USB_1/2 front panel.

**Comment by jacoweb** [comment]
Cool. Sorry its just cosmetic with the thunderbolt issue.  Now i have another issue, i cant get past the black screen of death. Did a clean format. Dunno what to do. Have made a custom SSDT for my GFX.

**Comment by koush** [comment]
use agdpfix. i don't prefer that, but you likely generated your ssdt patch incorrectly.

**Comment by jacoweb** [comment]
I got it working without agdpfix. I changed from Displayport to HDMI. Dunno why, but it works now. Need to go deeper into it.
