### ISSUE TITLE
Dual GPU

### ISSUE THREAD

**Issue by islesofmike** [koush/EFI-X99#6]
I followed your method and got macOS working with a single 980 Ti card on my X99P-SLI.

I use a E5-2683 V3 CPU and have amended the plist as instructed to have 27 instead of 19.

However I added a second card and now macOS reboots on "PCI Configuration Begin" during startup.

The second card is a Titan X (Pascal) and I only intend to use this in Windows. I have tried the card in various slots and have ensured that the 980 Ti is the primary but to no avail.

Any ideas please?

Thanks,

Mike

**Comment by islesofmike** [comment]
I think the issue might be related to the NVME drive.

I followed another guide and installed macOS from USB (guide linked below).

https://nickwoodhams.com/x99-hackintosh-guide-part-2-creating-clover-install-usb/

I have not added anything to do with my NVME M.2 to this install but I did leave the card in situ. I installed Clover to the HDD post install and installed the Ethernet drivers using MultiBeast afterwards.

I can live without being able to access my NVME drive in macOS thankfully.

There seems to be less stuff installed using Nick Woodhams method as opposed to your method. I hope I haven't missed anything vital. The system seems stable enough though.

Thanks for your guide as it is the reason I tried all this in the first place.

Mike

**Comment by koush** [comment]
I have an NVME drive myself. But my DSDT patches may be causing issues with yours. Try deleting this file, and booting with your NVME installed:

https://github.com/koush/EFI-X99/blob/master/CLOVER/ACPI/patched/SSDT-NVMe-Pcc.aml

**Comment by koush** [comment]
You can also generate your own NVME patch if you manage to get it booting without NVME support using this script (which is also stored on the EFI for convenience):


https://github.com/koush/EFI-X99/blob/master/CLOVER/bin/generate-spoof-nvme.sh

**Comment by islesofmike** [comment]
I have it all working now using Nick Woodhams method. 

I have the NVME drive working too, I installed IONVMeFamily using kext utility.

Thanks again for your help.

Mike
