### ISSUE TITLE
Thunderbolt not working

### ISSUE THREAD

**Issue by cassiuscai** [koush/EFI-X99#7]
About This Mac -> System Report -> Thunderbolt: No drivers are loaded.

**Comment by koush** [comment]
This is normal. Thunderbolt egpu works for me. Using one now.
![mac_pro_and_about_this_mac](https://user-images.githubusercontent.com/73924/27757807-7aff19b0-5dbb-11e7-8724-f927d6929d7e.png)

**Comment by koush** [comment]
You'll need to use Windows to update your thunderbolt firmware to the latest.

**Comment by koush** [comment]
![mac_pro](https://user-images.githubusercontent.com/73924/27757838-f265ac08-5dbb-11e7-955b-e487c3668777.png)

**Comment by cassiuscai** [comment]
Thanks
