### ISSUE TITLE
overclocking

### ISSUE THREAD

**Issue by mdkfilm** [koush/EFI-X99#8]
First, thank you so much for creating this I am up and running with my 6950x and x99p sli at home.  I didn't know exactly where to post this because its not an issue.  I was just curious if you had gotten overclocking working stable on the board with Hackintosh.  Currently I left my bios setting to default because when I updated from f22 firmware to f24 and selected the 6950x in the dropdown on the bios which allowed for over clocking to 4.2 or 4.3 I guess through speed stepping.  Forgive me this is all new to me, I am a video editor by trade.  Really I am just another frustrated Mac professional.  Anyway, after selecting 6950x and booting the Geekbench performance was off the charts.  However, after about 5 minutes of exporting a heavy timeline in Premiere Pro the computer just reboots.  It will wait longer to reboot if I don't use premiere or some heavy resource app but still will reboot.  It did this overnight.  The machine is certainly fantastic the way it is now capping at 3.4, verified by the intel gadget, but I was just curious if you had found any stable overclock.  FYI I ran the gigabyte update to thunderbolt, which is now at firmware 16.2 or so and put it in legacy thunderbolt security on the bios.  I am now able to attach a sonnet 3 bay thunderbolt expansion chassis and the hack pro sees it on boot.  I verified it because I had 2 Blackmagic cards, one internal and one in the chassis.  

Thanks again for this fantastic contribution.

**Comment by koush** [comment]
I don't use speed stepping, I just enable XMP. https://github.com/koush/EFI-X99#xmp
That's just an easy mode overclock, but is reliant on your RAM being able to support it. I think I set the RAM mode to stability as well (or something like that) to prevent reboots. That puts my max frequency at 4ghz. 4.3 is quite high, may not be achievable, which may be why you are rebooting.

You can probably tune it to OC better with voltage settings and high end cooling. If it's rebooting, you might need to tweak that.

I'm also using a akitio node eGPU. Works great.
